defaults: &defaults
  working_directory: ~/tankthinks.net

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: clojure:lein-2.7.1-alpine

    steps:
      - checkout

      - run: lein run
      - run: mkdir -p workspace
      - run: cp -rv resources/public workspace/
          
      - persist_to_workspace:
          root: workspace
          paths:
            - public

  deploy:
    <<: *defaults
    docker:
      - image: mesosphere/aws-cli:latest

    steps:
      - attach_workspace:
          at: workspace

      - run:
        name: Deploy to s3
        command: |
          aws -v

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build
