version: 2
jobs:
  build:
    docker:
      - image: clojure:lein-2.7.1-alpine

    working_directory: /tmp
    steps:
      - run:
          name: Create Static Website
          command: |
            lein run

      - store_artifacts:
          path: /tmp/public/resources
