defaults: &defaults
  working_directory: ~/tankthinks.net

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: clojure:lein-2.7.1-alpine

    steps:
      - checkout

      - run:
          name: Create Static Website
          command: |
            lein run;
            pwd;
            ls -lart;
            ls -lart resources/public;

      - persist_to_workspace:
          paths:
            - resources/public

  deploy:
    <<: *defaults
    docker:
      - image: mesosphere/aws-cli:latest

    steps:
      - attach_workspace:
          at: resources/public

      - run:
        name: Deploy to s3
        command: |
          aws -v

workflows:
  version: 2

  btd:
    jobs:
      - build
      - deploy:
          requires:
            - build
