version: 2
jobs:
  build:
    working_directory: ~/tankthinks.net
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.8.3-node-browsers-legacy
    environment:
#      LEIN_ROOT: nbd
#      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: tankthinks.net-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: tankthinks.net-{{ checksum "project.clj" }}
      - run: lein do run
      - store_artifacts:
          path: resources/public
          destination: public
